#!/bin/bash

function require_brew() {
  running "brew install $1 $2"
  brew list $1 > /dev/null 2>&1 | true
  if [[ ${PIPESTATUS[0]} != 0 ]]; then
    action "brew install $1"
    brew install $1 $2
    if [[ $? != 0 ]]; then
      error "failed to install $1! aborting..."
      exit -1
    fi
  fi
  ok
}

function cask_install() {
  running "brew install --casks $1 $2"
  brew search --casks $1 > /dev/null 2>&1 | true
  if [[ ${PIPESTATUS[0]} != 0 ]]; then
    action "brew install --casks $1"
    brew install --casks $1 $2
    if [[ $? != 0 ]]; then
      error "failed to install $1! aborting..."
      exit -1
    fi
  fi
  ok
}

########## BREW PKGS ##########
running "installing htop"
require_brew htop

running "installing httpie"
require_brew httpie

########## APPS ###########

#### DEVELOPMENT ####
yes_or_no "would you like to install iterm?"
if confirmed; then
  cask_install iterm2
fi

#### MEDIA ####
yes_or_no "would you like to install vlc?"
if confirmed; then
  cask_install vlc
fi

yes_or_no "would you like to install spotify?"
if confirmed; then
  cask_install spotify
fi

#### COMMUNICATION ####
yes_or_no "would you like to install slack?"
if confirmed; then
  cask_install slack
fi

#### MISC ####
yes_or_no "would you like to install google chrome?"
if confirmed; then
  cask_install google-chrome
fi

yes_or_no "would you like to install alfred?"
if confirmed; then
  cask_install alfred
fi

yes_or_no "would you like to install rectangle?"
if confirmed; then
  cask_install rectangle
fi

yes_or_no "would you like to install itsycal?"
if confirmed; then
  cask_install itsycal
fi

yes_or_no "would you like to install vscode?"
if confirmed; then
  cask_install visual-studio-code
fi

bot "chosen brew and brew cask packages installed successfully"
